'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'KZT',maximumFractionDigits:2}).format((v||0)/100);
const number=v=>new Intl.NumberFormat('ru-RU').format(v||0);
const pages={dashboard:['Обзор','Обзор платформы','Ключевые показатели вашей команды.','▦'],coaches:['Тренеры','Тренеры','Зарегистрированные тренеры на платформе.','♧'],players:['Игроки','Игроки','Игроки и родители, завершившие регистрацию.','♙'],groups:['Группы','Учебные группы','Составы, тренеры и расписание групп.','◫'],sessions:['Тренировки','Тренировки','Занятия за выбранный период.','◷'],requests:['Заявки','Заявки','Заявки на занятия и в группы за выбранный период.','↗'],clubs:['Клубы','Клубы','Теннисные клубы, города и адреса.','⌂'],courts:['Корты','Корты','Площадки и их доступность внутри клубов.','⊞'],finance:['Финансы','Учёт оплат','Оплаты, полученные тренерами от учеников.','₸'],reports:['Отчёты','Отчёты и выгрузки','Данные для анализа в CSV.','▤']};
const labels={fullName:'Имя',telegramId:'Telegram ID',username:'Telegram',email:'Email',city:'Город',venue:'Клуб',bio:'О себе',role:'Роль',name:'Название',coachName:'Тренер',playerName:'Игрок',place:'Место',memberCount:'Участников',date:'Дата',time:'Время',status:'Статус',createdDate:'Дата заявки',comment:'Комментарий',start:'Начало',end:'Окончание',durationMinutes:'Минут',amount:'Сумма',hours:'Часы',payer:'Плательщик',group:'Группа',address:'Адрес',clubId:'Клуб',cityId:'Город',surface:'Покрытие',id:'ID',type:'Тип',reason:'Причина',showToStudents:'Виден ученикам',syncToCalendar:'Календарь',days:'Дни недели',members:'Участники',absent:'Отсутствовали'};
const statusLabels={scheduled:'Запланирована',completed:'Завершена',cancelled:'Отменена',pending:'Ожидает',accepted:'Принята',rejected:'Отклонена',active:'Открыт',maintenance:'Обслуживание',closed:'Закрыт',coach:'Тренер',player:'Игрок',parent:'Родитель'};
const columns={coaches:['fullName','city','venue','email'],players:['fullName','role','city','email'],groups:['name','coachName','place','memberCount'],sessions:['name','coachName','date','time','status'],requests:['playerName','coachName','createdDate','status'],clubs:['name','city','address'],courts:['name','clubId','surface','status'],finance:['date','playerName','coachName','amount','hours']};
let csrf='',page='dashboard',pageNumber=1,options={cities:[],clubs:[],coaches:[]},items=[],filters={},requestVersion=0;
async function api(path,body){const response=await fetch('/api/admin/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});const data=await response.json();if(!response.ok){if(response.status===401&&path!=='login')showLogin();throw Error(data.error||'Не удалось загрузить данные');}return data;}
function showLogin(){$('#app').hidden=true;$('#login').hidden=false;csrf='';}
function query(extra={}){return new URLSearchParams({from:$('#from').value,to:$('#to').value,...filters,...extra}).toString();}
function download(resource){location.assign('/api/admin/report?'+query({resource}));}
function format(key,value){if(key==='amount')return money(value);if(key==='clubId')return options.clubs.find(c=>c.id===value)?.name||value;if(key==='cityId')return options.cities.find(c=>c.id===value)?.name||value;if(key==='status'||key==='role')return statusLabels[value]||value;if(typeof value==='boolean')return value?'Да':'Нет';if(Array.isArray(value))return value.join(', ');return value??'—';}
function cell(key,value){const text=esc(format(key,value)||'—');return key==='status'?`<span class="badge ${esc(value)}">${text}</span>`:text;}
function setDates(days){const now=new Date(Date.now()+5*3600000);const end=now.toISOString().slice(0,10);now.setUTCDate(now.getUTCDate()-days+1);$('#from').value=now.toISOString().slice(0,10);$('#to').value=end;}
function chart(series,key){const max=Math.max(1,...series.map(x=>x[key]));const width=640,height=180,step=width/series.length;return `<svg class="chart" viewBox="0 0 660 215" role="img" aria-label="${key==='payments'?'Оплаты тренерам':'Завершённые тренировки'} по дням"><title>Динамика по дням выбранного периода</title>${[0,1,2,3].map(n=>`<line class="chart-line" x1="0" x2="640" y1="${20+n*60}" y2="${20+n*60}"/>`).join('')}${series.map((d,i)=>`<rect class="chart-bar" x="${i*step+step*.2}" y="${200-d[key]/max*height}" width="${Math.max(.4,step*.6)}" height="${d[key]/max*height}" rx="2"><title>${esc(d.date)}: ${esc(key==='payments'?money(d[key]):number(d[key]))}</title></rect>`).join('')}<text x="0" y="12">${esc(key==='payments'?money(max):number(max))}</text></svg><div class="chart-labels"><span>${esc(series[0]?.date)}</span><span>${esc(series.at(-1)?.date)}</span></div>`;}
function stat(title,value,note,icon,highlight=false){return `<article class="stat ${highlight?'highlight':''}"><div class="stat-top"><span>${title}</span><span class="stat-icon">${icon}</span></div><strong>${value}</strong><small>${note}</small></article>`;}
function renderDashboard(d){$('#content').innerHTML=`<div class="stats">${stat('Тренеры',number(d.coaches),'Завершили регистрацию · всего','♧')}${stat('Игроки и родители',number(d.players),'Завершили регистрацию · всего','♙')}${stat('Завершённые тренировки',number(d.completed),'За выбранный период','◷')}${stat('Оплаты тренерам',money(d.payments),number(d.paymentCount)+' записей за период','↗',true)}</div><div class="chart-grid"><section class="panel"><div class="panel-heading"><div><h2>Динамика оплат</h2><p>Записанные оплаты по дням · ₸</p></div><span class="badge">За период</span></div>${chart(d.series,'payments')}</section><section class="panel"><div class="panel-heading"><div><h2>Тренировки</h2><p>Статусы занятий за период</p></div></div>${Object.entries(d.statuses).map(([key,count])=>`<div class="status-row"><span class="status-label"><i class="dot ${key}"></i>${statusLabels[key]}</span><b>${number(count)}</b></div>`).join('')}<div class="status-row"><span>Группы · всего</span><b>${number(d.groups)}</b></div><div class="status-row"><span>Ожидающие заявки · всего</span><b>${number(d.pending)}</b></div></section></div><section class="panel"><div class="panel-heading"><div><h2>Завершённые занятия</h2><p>Количество тренировок по дням</p></div></div>${chart(d.series,'completed')}</section><div class="notice"><b>Как считаем показатели</b><br>Тренеры, игроки, группы и ожидающие заявки — текущие значения за всё время. Тренировки — по дате занятия, оплаты — по дате внесённой оплаты. Часовой пояс: UTC+5. Суммы отражают оплаты тренерам, а не выручку TopCoach.</div>`;}
function selectOptions(values,current){return values.map(([value,label])=>`<option value="${esc(value)}" ${String(value)===String(current)?'selected':''}>${esc(label)}</option>`).join('');}
function toolbar(){const statuses=page==='sessions'?['scheduled','completed','cancelled']:page==='requests'?['pending','accepted','rejected']:page==='courts'?['active','maintenance','closed']:[];return `<form id="filters" class="toolbar"><input name="q" aria-label="Поиск" placeholder="Поиск по имени, названию или ID…" value="${esc(filters.q||'')}" maxlength="200">${['coaches','players','clubs'].includes(page)?`<select name="city" aria-label="Город">${selectOptions([['','Все города'],...options.cities.map(c=>[c.name,c.name])],filters.city)}</select>`:''}${['groups','sessions','requests','finance'].includes(page)?`<select name="coach" aria-label="Тренер">${selectOptions([['','Все тренеры'],...options.coaches.map(c=>[c.id,c.name])],filters.coach)}</select>`:''}${statuses.length?`<select name="status" aria-label="Статус">${selectOptions([['','Все статусы'],...statuses.map(s=>[s,statusLabels[s]])],filters.status)}</select>`:''}<button class="secondary" type="submit">Найти</button>${['clubs','courts'].includes(page)?'<button id="create" class="primary" type="button">+ Добавить</button>':''}</form>`;}
function renderTable(data){items=data.items;const cols=columns[page];$('#content').innerHTML=`${page==='finance'?`<div class="finance-summary"><div><small>Оплаты по выбранным фильтрам</small><br><strong>${money(data.summary.amount)}</strong></div><div><small>${number(data.total)} платежей · ${number(data.summary.hours)} оплаченных часов</small></div></div>`:''}${page==='finance'?'<div class="notice"><b>Учёт оплат тренерам</b><br>Суммы в тенге; оплата и часы записаны тренером. Изменение платежей в админке недоступно. Экспорт включает все строки с выбранными фильтрами.</div>':''}<section class="panel">${toolbar()}<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${labels[c]}</th>`).join('')}<th>Действия</th></tr></thead><tbody>${items.map((row,i)=>`<tr>${cols.map(c=>`<td>${cell(c,row[c])}</td>`).join('')}<td><button class="row-action" data-detail="${i}">Подробнее ↗</button>${['clubs','courts'].includes(page)?`<button class="row-action" data-edit="${i}">Изменить</button>`:''}</td></tr>`).join('')}</tbody></table></div>${items.length?'':'<div class="empty"><b>Пока нет записей</b>Попробуйте изменить поиск, фильтры или период.</div>'}<div class="pager"><span>Найдено: ${number(data.total)}</span><div><button id="previous" class="secondary" ${pageNumber<=1?'disabled':''}>←</button><span>${pageNumber} / ${Math.max(1,Math.ceil(data.total/data.pageSize))}</span><button id="next" class="secondary" ${pageNumber*data.pageSize>=data.total?'disabled':''}>→</button></div></div></section>${['coaches','players','groups','clubs','courts'].includes(page)?'<p class="muted">Список за всё время. Выбранный период применяется к тренировкам, заявкам и оплатам.</p>':''}`;
$('#filters').onsubmit=e=>{e.preventDefault();filters=Object.fromEntries(new FormData(e.target));pageNumber=1;load();};$('#previous').onclick=()=>{pageNumber--;load();};$('#next').onclick=()=>{pageNumber++;load();};$('#create')?.addEventListener('click',()=>edit());document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>details(items[Number(b.dataset.detail)]));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(items[Number(b.dataset.edit)]));}
function openDialog(title,html){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;$('#dialog').showModal();}
function details(row){const fields=Object.keys(labels).filter(k=>k in row);openDialog(row.fullName||row.name||'Карточка записи',`<dl class="details">${fields.map(k=>`<dt>${esc(labels[k])}</dt><dd>${esc(format(k,row[k]))}</dd>`).join('')}</dl>`);}
function edit(row){const resource=page;const fields=resource==='clubs'?['name','cityId','address']:['name','clubId','surface','status'];const field=f=>{const choices=f==='cityId'?options.cities.map(c=>[c.id,c.name]):f==='clubId'?options.clubs.map(c=>[c.id,c.name+' · '+c.city+' · '+c.address]):f==='status'?['active','maintenance','closed'].map(s=>[s,statusLabels[s]]):null;return `<label>${labels[f]}${choices?`<select name="${f}" required>${selectOptions([['','Выберите…'],...choices],row?.[f])}</select>`:`<input name="${f}" value="${esc(row?.[f]||'')}" required maxlength="250">`}</label>`;};openDialog(row?'Изменить запись':resource==='clubs'?'Новый клуб':'Новый корт',`<form id="edit-form" class="edit-form">${fields.map(field).join('')}<p id="edit-error" class="error" role="alert"></p><div class="form-actions">${row?'<button id="delete" type="button" class="secondary danger">Удалить</button>':''}<button class="primary" type="submit">Сохранить</button></div></form>`);let busy=false;const save=async payload=>{if(busy)return;busy=true;const buttons=$('#edit-form').querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await api(resource,payload);options=await api('options');$('#dialog').close();await load();}catch(e){$('#edit-error').textContent=e.message;}finally{busy=false;buttons.forEach(b=>b.disabled=false);}};$('#edit-form').onsubmit=e=>{e.preventDefault();save({operation:row?'update':'create',id:row?.id,data:Object.fromEntries(new FormData(e.target))});};$('#delete')?.addEventListener('click',()=>{if(confirm('Удалить «'+row.name+'»? Это действие нельзя отменить.'))save({operation:'delete',id:row.id});});}
function renderReports(){$('#content').innerHTML=`<div class="notice"><b>Одинаковые периоды на экране и в выгрузке</b><br>CSV содержит часовой пояс и границы периода. Оплаты экспортируются в тенге с точностью до тиына. Списки людей, групп и справочники включают все текущие записи.</div><div class="report-grid">${Object.keys(columns).map(key=>`<article class="report-card"><span class="eyebrow">CSV / UTF-8</span><h2>${pages[key][1]}</h2><p>${pages[key][2]}</p><button class="secondary" data-report="${key}">↓ Скачать CSV</button></article>`).join('')}</div>`;document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>download(b.dataset.report));}
async function load(){const version=++requestVersion;$('#page-error').textContent='';$('#content').innerHTML='<div class="loading">Загружаем данные…</div>';try{if(page==='reports'){renderReports();return;}const data=await api((page==='dashboard'?'dashboard':page)+'?'+query({page:pageNumber}));if(version!==requestVersion)return;if(page==='dashboard')renderDashboard(data);else renderTable(data);}catch(e){if(version!==requestVersion)return;$('#content').innerHTML='<div class="empty"><b>Не удалось загрузить данные</b><button id="retry" class="secondary">Повторить</button></div>';$('#page-error').textContent=e.message;$('#retry').onclick=load;}}
function navigate(next,push=true){page=pages[next]?next:'dashboard';pageNumber=1;filters={};if(push)history.pushState({},'',page==='dashboard'?'/admin':'/admin/'+page);$('#title').textContent=pages[page][1];$('#description').textContent=pages[page][2];$('#breadcrumb').textContent=pages[page][0];document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#export').hidden=page==='reports';load();}
async function start(account){csrf=account.csrf;$('#account').textContent=account.username;$('#login').hidden=true;$('#app').hidden=false;options=await api('options');navigate(location.pathname.split('/')[2]||'dashboard',false);}
$('#nav').innerHTML=Object.entries(pages).map(([key,p])=>`<a href="${key==='dashboard'?'/admin':'/admin/'+key}" data-page="${key}"><span>${p[3]}</span>${p[0]}</a>`).join('');$('#nav').onclick=e=>{const a=e.target.closest('a');if(a){e.preventDefault();navigate(a.dataset.page);}};
$('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;$('#login-error').textContent='';try{const data=await api('login',Object.fromEntries(new FormData(e.target)));e.target.reset();history.replaceState({},'','/admin');await start(data);}catch(error){$('#login-error').textContent=error.message;}finally{button.disabled=false;}};
$('#logout').onclick=async()=>{try{await api('logout',{});requestVersion++;showLogin();history.replaceState({},'','/admin/login');}catch(e){$('#page-error').textContent=e.message;}};
$('#period').onsubmit=e=>{e.preventDefault();pageNumber=1;load();};$('#preset').onchange=e=>{if(e.target.value!=='custom'){setDates(Number(e.target.value));pageNumber=1;load();}};['from','to'].forEach(id=>$('#'+id).onchange=()=>{$('#preset').value='custom';});$('#export').onclick=()=>download(page==='dashboard'?'finance':page);$('#close-dialog').onclick=()=>$('#dialog').close();window.onpopstate=()=>{if(csrf)navigate(location.pathname.split('/')[2]||'dashboard',false);};
setDates(30);api('me').then(start).catch(e=>{showLogin();if(e.message!=='Войдите в кабинет')$('#login-error').textContent=e.message;});
